post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
end

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
target ‘HealthKitDemo’ do
pod 'SVProgressHUD'
pod 'SnapKit'
pod 'Then'
pod 'Reusable'
pod 'SwifterBaseKit', '~> 0.3.0'
pod 'FDFullscreenPopGesture'

end